---
# Catalog Team - Base Kustomization
# Owner: catalog-team@example.com
# APIs: Products API
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: catalog-team-apis

namespace: gravitee-apis

commonLabels:
  app.kubernetes.io/managed-by: gko
  app.kubernetes.io/part-of: gravitee-apim
  team: catalog-team
  cost-center: CC-CATALOG-001

resources:
  - ../../../base/namespace.yaml
  - ../../../base/management-context.yaml
  - products-api/api-definition.yaml
  - products-api/api-plan.yaml

