# Catalog Team - UAT Environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: catalog-team-apis-uat

namespace: gravitee-apis-uat

resources:
  - ../../base

commonLabels:
  environment: uat
  team: catalog-team

patches:
  # UAT backend URL for Products API
  - target:
      kind: ApiDefinition
      name: products-api
    patch: |-
      - op: replace
        path: /spec/proxy/groups/0/endpoints/0/target
        value: http://products-service.catalog-team-uat.svc.cluster.local:8080
      - op: add
        path: /metadata/labels/environment
        value: uat
      - op: replace
        path: /spec/analytics/logging/mode
        value: CLIENT_PROXY
      - op: replace
        path: /spec/analytics/logging/content
        value: HEADERS

  # Update ManagementContext for UAT
  - target:
      kind: ManagementContext
      name: gravitee-apim-context
    patch: |-
      - op: replace
        path: /spec/baseUrl
        value: http://gravitee-management-api.gravitee-apim-uat.svc.cluster.local:8083
      - op: replace
        path: /spec/environmentId
        value: uat

