# Development Environment Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gravitee-apis-dev

resources:
  - ../../base

commonLabels:
  environment: development

patches:
  # Dev backend URL
  - target:
      kind: ApiDefinition
      name: my-api
    patch: |-
      - op: replace
        path: /spec/proxy/groups/0/endpoints/0/target
        value: http://my-service.my-team-dev.svc.cluster.local:8080
      - op: add
        path: /metadata/labels/environment
        value: development
      - op: replace
        path: /spec/flows/0/pre/0/configuration/rate/limit
        value: 1000
      - op: replace
        path: /spec/analytics/logging/content
        value: PAYLOADS

  # Dev ManagementContext
  - target:
      kind: ManagementContext
      name: gravitee-apim-context
    patch: |-
      - op: replace
        path: /spec/baseUrl
        value: http://gravitee-management-api.gravitee-apim-dev.svc.cluster.local:8083
      - op: replace
        path: /spec/environmentId
        value: development

