---
# Commerce Team - Base Kustomization
# Owner: commerce-team@example.com
# APIs: Orders API
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: commerce-team-apis

namespace: gravitee-apis

commonLabels:
  app.kubernetes.io/managed-by: gko
  app.kubernetes.io/part-of: gravitee-apim
  team: commerce-team
  cost-center: CC-COMMERCE-001

resources:
  - ../../../base/namespace.yaml
  - ../../../base/management-context.yaml
  - orders-api/api-definition.yaml
  - orders-api/api-plan.yaml

