# UAT Environment Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gravitee-apis-uat

resources:
  - ../../base

commonLabels:
  environment: uat

patches:
  # UAT backend URL
  - target:
      kind: ApiDefinition
      name: my-api
    patch: |-
      - op: replace
        path: /spec/proxy/groups/0/endpoints/0/target
        value: http://my-service.my-team-uat.svc.cluster.local:8080
      - op: add
        path: /metadata/labels/environment
        value: uat

  # UAT ManagementContext
  - target:
      kind: ManagementContext
      name: gravitee-apim-context
    patch: |-
      - op: replace
        path: /spec/baseUrl
        value: http://gravitee-management-api.gravitee-apim-uat.svc.cluster.local:8083
      - op: replace
        path: /spec/environmentId
        value: uat

